### ISSUE TITLE
Where to process the robust04 data fed into cedr_x model?

### ISSUE THREAD

**Issue by yiyaxiaozhi** [Georgetown-IR-Lab/OpenNIR#42]
Thanks for your wonderful work again.
If I want to change the input sequence of BERT, which file should I change？

**Comment by seanmacavaney** [comment]
Do you mean the query and document text? By default, it uses the text it stores in the docstore (defined [here](https://github.com/Georgetown-IR-Lab/OpenNIR/blob/master/onir/datasets/robust.py#L55)) for documents and the topics file for queries (defined [here](https://github.com/Georgetown-IR-Lab/OpenNIR/blob/master/onir/datasets/robust.py#L82)).

If you want, you can override these values by giving different `_doc_rawtext` and `_query_rawtext` implementations. Here are the default implementations:

```python
    def _doc_rawtext(self, record):
        docstore = self._get_docstore()
        return docstore.get_raw(record['doc_id'])
    def _query_rawtext(self, record):
        return self._load_queries_base(self.config['subset'])[record['query_id']]
```

If you want to change how the tokenised query/document are fed into BERT, here's the code for that: https://github.com/Georgetown-IR-Lab/OpenNIR/blob/master/onir/vocab/bert_vocab.py#L174

Hope this helps!

**Comment by yiyaxiaozhi** [comment]
Thanks a lot, that is the file that I want to change!
